In [3]:
import numpy as np

In [5]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
my_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(my_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])